# Generated by Django 5.2 on 2025-04-24 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='monster_ac',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='monster_attack_bonus',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='monster_damage',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='monster_hp',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='monster_name',
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('attack_bonus', models.IntegerField()),
                ('damage', models.CharField(max_length=50)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='campaigns.encounter')),
            ],
        ),
    ]
