# Generated by Django 5.2 on 2025-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_encounter_monster_ac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='stats',
        ),
        migrations.AddField(
            model_name='npc',
            name='ac',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='npc',
            name='attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='damage',
            field=models.CharField(default='1d6', max_length=50),
        ),
        migrations.AddField(
            model_name='npc',
            name='hp',
            field=models.IntegerField(default=10),
        ),
    ]
