# Generated by Django 5.2 on 2025-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_npc_stats_npc_ac_npc_attack_bonus_npc_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='rolls',
            field=models.TextField(blank=True, default=''),
        ),
    ]
